update test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,13 +17,13 @@ jobs:
                   node-version: '12'
             - name: Build (TS->JS)
               run: tsc
-            - uses: thezion/github-action-env-vars@develop
+            - uses: ./
               with:
                   json-url: 'https://raw.githubusercontent.com/thezion/github-action-env-vars/master/public/source.json'
                   preset: 'vue'
                   filename: 'public/actual-vue'
             - name: File Comparison
-              run: cmp -s public/expect-vue public/actual-vue || ( echo 'test failed' & exit 1 )
+              run: (cmp -s public/expect-vue public/actual-vue && echo 'test passed') || (echo 'test failed' && exit 1)
             # - name: Deploy to GitHub Pages
             #   uses: peaceiris/actions-gh-pages@v3
             #   with:
